/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as BienvenueRouteImport } from './routes/bienvenue'
import { Route as CalculRouteImport } from './routes/calcul'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as HistoriqueRouteImport } from './routes/historique'
import { Route as HomeRouteImport } from './routes/home'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as PrixRouteImport } from './routes/prix'
import { Route as ProfilRouteImport } from './routes/profil'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const BienvenueRoute = BienvenueRouteImport.update({
  id: '/bienvenue',
  path: '/bienvenue',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculRoute = CalculRouteImport.update({
  id: '/calcul',
  path: '/calcul',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriqueRoute = HistoriqueRouteImport.update({
  id: '/historique',
  path: '/historique',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const PrixRoute = PrixRouteImport.update({
  id: '/prix',
  path: '/prix',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/bienvenue': typeof BienvenueRoute
  '/calcul': typeof CalculRoute
  '/design-system': typeof DesignSystemRoute
  '/historique': typeof HistoriqueRoute
  '/home': typeof HomeRoute
  '/notifications': typeof NotificationsRoute
  '/parametres': typeof ParametresRoute
  '/prix': typeof PrixRoute
  '/profil': typeof ProfilRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/bienvenue': typeof BienvenueRoute
  '/calcul': typeof CalculRoute
  '/design-system': typeof DesignSystemRoute
  '/historique': typeof HistoriqueRoute
  '/home': typeof HomeRoute
  '/notifications': typeof NotificationsRoute
  '/parametres': typeof ParametresRoute
  '/prix': typeof PrixRoute
  '/profil': typeof ProfilRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/bienvenue': typeof BienvenueRoute
  '/calcul': typeof CalculRoute
  '/design-system': typeof DesignSystemRoute
  '/historique': typeof HistoriqueRoute
  '/home': typeof HomeRoute
  '/notifications': typeof NotificationsRoute
  '/parametres': typeof ParametresRoute
  '/prix': typeof PrixRoute
  '/profil': typeof ProfilRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/bienvenue'
    | '/calcul'
    | '/design-system'
    | '/historique'
    | '/home'
    | '/notifications'
    | '/parametres'
    | '/prix'
    | '/profil'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/bienvenue'
    | '/calcul'
    | '/design-system'
    | '/historique'
    | '/home'
    | '/notifications'
    | '/parametres'
    | '/prix'
    | '/profil'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/bienvenue'
    | '/calcul'
    | '/design-system'
    | '/historique'
    | '/home'
    | '/notifications'
    | '/parametres'
    | '/prix'
    | '/profil'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  BienvenueRoute: typeof BienvenueRoute
  CalculRoute: typeof CalculRoute
  DesignSystemRoute: typeof DesignSystemRoute
  HistoriqueRoute: typeof HistoriqueRoute
  HomeRoute: typeof HomeRoute
  NotificationsRoute: typeof NotificationsRoute
  ParametresRoute: typeof ParametresRoute
  PrixRoute: typeof PrixRoute
  ProfilRoute: typeof ProfilRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bienvenue': {
      id: '/bienvenue'
      path: '/bienvenue'
      fullPath: '/bienvenue'
      preLoaderRoute: typeof BienvenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calcul': {
      id: '/calcul'
      path: '/calcul'
      fullPath: '/calcul'
      preLoaderRoute: typeof CalculRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historique': {
      id: '/historique'
      path: '/historique'
      fullPath: '/historique'
      preLoaderRoute: typeof HistoriqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prix': {
      id: '/prix'
      path: '/prix'
      fullPath: '/prix'
      preLoaderRoute: typeof PrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  BienvenueRoute: BienvenueRoute,
  CalculRoute: CalculRoute,
  DesignSystemRoute: DesignSystemRoute,
  HistoriqueRoute: HistoriqueRoute,
  HomeRoute: HomeRoute,
  NotificationsRoute: NotificationsRoute,
  ParametresRoute: ParametresRoute,
  PrixRoute: PrixRoute,
  ProfilRoute: ProfilRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.ts'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
